### ISSUE TITLE
The Task 4.1 has a bug

### ISSUE THREAD

**Issue by ZehuaLiuY** [UoB-CS-AVAI/Week1-an-introduction-to-Pytorch#1]
in the last line of the code we currently have:
``` python
out_obj_ids, out_mask_logits = None, None
```

When I build the video predictor, and use the add_new_points_or_box interface, I got a problem when I run this code cell:
``` text
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[50], line 14
     11 inference_state = v_predictor.init_state(video_path = video_dir)
     12 v_predictor.reset_state(inference_state)
---> 14 out_obj_ids, out_mask_logits = v_predictor.add_new_points_or_box(
     15     inference_state = inference_state,
     16     frame_idx = ann_frame_idx,
     17     obj_id = ann_obj_id,
     18     box = box,
     19     
     20 )

ValueError: too many values to unpack (expected 2)

```

When I add **_,** before the first parameter it runs.
So do I need to add this placeholder variable?

**Comment by JoanneLin168** [comment]
@ZehuaLiuY Well I didn't add `_ = None` because that almost makes no sense? (Not even sure _ is saved to memory anyway)

You are right that there needs to be 3 variables to store the output of `v_predictor`; if you look into the [source code](https://github.com/facebookresearch/segment-anything-2/blob/main/sam2/sam2_video_predictor.py#L310), you can see that it returns the following: `frame_idx, obj_ids, video_res_masks`.

I can see how it can be unclear though, perhaps I will change how that question is set out to be more clear.

Hopefully that clears things up.
